#!/usr/bin/env python3

import sys
import lexer

if __name__ == '__main__' :
	if len(sys.argv) != 4:
		print("INVALID argument count: LUTHER accepts exactly 3 arguments.", file=sys.stderr)
	else:
		lexer.lexer(sys.argv[1], sys.argv[2], sys.argv[3])